default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Получаем номер сборки из переменной окружения
    build_number = ENV["BUILD_NUMBER"]
    puts("Using build number: #{build_number}")
    # Сборка приложения
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )
    # Загрузка в TestFlight
    upload_to_testflight(
      api_key: app_store_connect_api_key(
        key_id: "KEY_ID",           # Идентификатор ключа из Apple Developer Portal
       Issuer_id: "ISSUER_ID",     # Идентификатор пользователя, выпустившего ключ
        key_filepath: "fastlane/auth.p8"  # Путь к файлу с ключом
      )
    )
  end
end 
